services:
  - type: web
    name: php-app
    env: docker
    envVars:
      - key: DB_HOST
        value: sql.freedb.tech
      - key: DB_PORT
        value: 3306
      - key: DB_NAME
        value: freedb_kiwi_db
      - key: DB_USER
        value: freedb_kiwiuser
      - key: DB_PASS
        value: Ej9xCX*Rz%?TT*E
